### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by OnionNinja** [timroes/quiz#5]
The `src/index.html` gives me several missing file errors: `scripts/app.min.js`,  `scripts/templates.js`, `styles/app.css` . Can those files be added?

**Comment by timroes** [comment]
You cannot just open the HTML file in your browser. It looks like you are trying to do this. Either look in the readme how to use the prebuilt python server or the how to contribute section, if you prefer running the build version in node js.

If the error is caused by either of the ways described in the readme, please give some more information how you tried to start it.

**Comment by OnionNinja** [comment]
Yes. I'm using the release files 0.1.1 
Download > Extract > cd > python src/server.py

Thanks for the new quiz.

**Comment by timroes** [comment]
True that. Very confusing and something forgotten. You cannot use the Source packages from the release package, only the manually uploaded once (which in case of 0.1.1 I didn't do - will try to upload it during the next days).

**Comment by OnionNinja** [comment]
:+1:
